from fastapi import APIRouter
from fastapi.responses import FileResponse

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet

from reportlab.lib.pagesizes import letter

import os


# =========================================
# ROUTER
# =========================================

router = APIRouter(

    prefix="/pdf",

    tags=["PDF Report"]

)


# =========================================
# GENERATE PDF REPORT
# =========================================

@router.get("/generate")

def generate_pdf(

    prediction: str,

    confidence: str,

    scan_type: str = "brain"

):

    # =========================================
    # PDF PATH
    # =========================================

    pdf_dir = os.path.abspath(

        os.path.join(
            os.path.dirname(__file__),
            "../reports"
        )

    )

    os.makedirs(
        pdf_dir,
        exist_ok=True
    )

    pdf_path = os.path.join(
        pdf_dir,
        "oncovision_report.pdf"
    )

    # =========================================
    # PDF DOCUMENT
    # =========================================

    doc = SimpleDocTemplate(

        pdf_path,

        pagesize=letter

    )

    styles = getSampleStyleSheet()

    elements = []

    # =========================================
    # TITLE
    # =========================================

    title = Paragraph(

        "<font size=22><b>OncoVision AI Clinical Report</b></font>",

        styles["Title"]

    )

    elements.append(title)

    elements.append(
        Spacer(1, 20)
    )

    # =========================================
    # BASIC DETAILS
    # =========================================

    content = f"""

    <font size=14>

    <b>Scan Type:</b> {scan_type}
    <br/><br/>

    <b>AI Prediction:</b> {prediction}
    <br/><br/>

    <b>Confidence Score:</b> {confidence}
    <br/><br/>

    <b>Clinical Severity:</b> High Risk
    <br/><br/>

    <b>AI Observation:</b>
    The uploaded scan shows abnormal tissue characteristics
    identified by the AI model.
    <br/><br/>

    <b>Recommendation:</b>
    Immediate consultation with a specialist doctor is advised
    for further clinical validation and treatment planning.
    <br/><br/>

    <b>Generated By:</b> OncoVision AI
    <br/><br/>

    <b>Disclaimer:</b>
    This report is AI-assisted and should not replace
    professional medical diagnosis.

    </font>

    """

    paragraph = Paragraph(

        content,

        styles["BodyText"]

    )

    elements.append(paragraph)

    # =========================================
    # BUILD PDF
    # =========================================

    doc.build(elements)

    # =========================================
    # RETURN PDF
    # =========================================

    return FileResponse(

        pdf_path,

        media_type="application/pdf",

        filename="OncoVision_AI_Report.pdf"

    )